### ISSUE TITLE
コンテナ上で実行した際のshared memoryエラー

### ISSUE THREAD

**Issue by makkimaki** [makkimaki/exp_docker_env#9]
チュートリアルコード実行時のエラー
```
(conda39) root@7ee9055fbd56:/work/tutorial/scripts# python 03_tutorial_infer.py 
Model building for efficientnet_b5 backbone
  0%|                                                     | 0/193 [00:00<?, ?it/s]ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
  1%|▏                                            | 1/193 [00:00<02:08,  1.50it/s]Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/miniconda3/envs/conda39/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/opt/miniconda3/envs/conda39/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/miniconda3/envs/conda39/lib/python3.9/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in _pin_memory_loop
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/opt/miniconda3/envs/conda39/lib/python3.9/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/opt/miniconda3/envs/conda39/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 289, in rebuild_storage_fd
    fd = df.detach()
  File "/opt/miniconda3/envs/conda39/lib/python3.9/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/opt/miniconda3/envs/conda39/lib/python3.9/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/opt/miniconda3/envs/conda39/lib/python3.9/multiprocessing/connection.py", line 513, in Client
    answer_challenge(c, authkey)
  File "/opt/miniconda3/envs/conda39/lib/python3.9/multiprocessing/connection.py", line 757, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/opt/miniconda3/envs/conda39/lib/python3.9/multiprocessing/connection.py", line 221, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/opt/miniconda3/envs/conda39/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/opt/miniconda3/envs/conda39/lib/python3.9/multiprocessing/connection.py", line 384, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
  1%|▏                                            | 1/193 [00:00<02:56,  1.09it/s]
Traceback (most recent call last):
  File "/work/tutorial/scripts/03_tutorial_infer.py", line 364, in <module>
    test_image_embeddings = get_image_embeddings(test_image_paths)
  File "/work/tutorial/scripts/03_tutorial_infer.py", line 339, in get_image_embeddings
    image_embeddings = feat.detach().cpu().numpy()
  File "/opt/miniconda3/envs/conda39/lib/python3.9/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 2102) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.
```

## 解決法？
`docker-compose.yml`内に追記が必要らしい。リンク: https://stackoverflow.com/questions/30210362/how-to-increase-the-size-of-the-dev-shm-in-docker-container

```
build:
  context: .
  shm_size: '2gb'
```

**Comment by makkimaki** [comment]
dockerコンテナのデフォルトは shared_memory = 64MB らしい。
https://anton0825.hatenablog.com/entry/2017/10/07/000000

**Comment by makkimaki** [comment]
```
(conda39) root@7ee9055fbd56:/work/tutorial/scripts# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         194G  193G  710M 100% /
tmpfs            64M     0   64M   0% /dev
tmpfs            15G     0   15G   0% /sys/fs/cgroup
shm              64M     0   64M   0% /dev/shm
/dev/sda1       194G  193G  710M 100% /work
tmpfs            15G   12K   15G   1% /proc/driver/nvidia
tmpfs            15G  4.0K   15G   1% /etc/nvidia/nvidia-application-profiles-rc.d
tmpfs           3.0G  1.1M  3.0G   1% /run/nvidia-persistenced/socket
udev             15G     0   15G   0% /dev/nvidia0
tmpfs            15G     0   15G   0% /proc/acpi
tmpfs            15G     0   15G   0% /proc/scsi
tmpfs            15G     0   15G   0% /sys/firmware
```

これの`shm`か。。

**Comment by makkimaki** [comment]
コミット：4eaff84 　で、shared memoryを増やしたつもり。  
見るべき場所は`shm              64M     0   64M   0% /dev/shm`ここ。
スクリプト実行すると減ってくる。

```
root@099a7aeddec5:/work# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         194G  192G  1.9G 100% /
tmpfs            64M     0   64M   0% /dev
tmpfs            15G     0   15G   0% /sys/fs/cgroup
shm              64M     0   64M   0% /dev/shm
/dev/sda1       194G  192G  1.9G 100% /work
tmpfs            15G   12K   15G   1% /proc/driver/nvidia
tmpfs            15G  4.0K   15G   1% /etc/nvidia/nvidia-application-profiles-rc.d
tmpfs           3.0G  1.1M  3.0G   1% /run/nvidia-persistenced/socket
udev             15G     0   15G   0% /dev/nvidia0
tmpfs            15G     0   15G   0% /proc/acpi
tmpfs            15G     0   15G   0% /proc/scsi
tmpfs            15G     0   15G   0% /sys/firmware
```
